# Generated by Django 5.0.1 on 2024-01-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
